import { crudRouter } from "../utils/crudRouter.js";

// registration_code / qr_code_data are auto-generated by trigger; checked_in fields
// are set by admin at the gate rather than via register_for_session.
const createFields = ["user_id", "conference_id"];
const updateFields = ["checked_in", "checked_in_at"];

export const registrationsRouter = crudRouter({
  table: "conference_registrations",
  createFields,
  updateFields,
  filterFields: ["conference_id", "user_id", "checked_in"],
  defaultOrder: { column: "created_at", ascending: false },
});
